defprotocol ApathyDrive.Mobile do
  def ability_value(mobile, ability)
  def accuracy_at_level(mobile, level)
  def attribute_at_level(mobile, attribute, level)
  def confused(mobile, room)
  def crits_at_level(mobile, level)
  def dodge_at_level(mobile, level)
  def enter_message(mobile)
  def exit_message(mobile)
  def held(mobile)
  def look_name(mobile)
  def magical_damage_at_level(mobile, level)
  def magical_resistance_at_level(mobile, level)
  def max_hp_at_level(mobile, level)
  def max_mana_at_level(mobile, level)
  def perception_at_level(mobile, level)
  def physical_damage_at_level(mobile, level)
  def physical_resistance_at_level(mobile, level)
  def send_scroll(mobile, html)
  def set_room_id(mobile, room_id)
  def spellcasting_at_level(mobile, level)
  def stealth_at_level(mobile, level)
  def tracking_at_level(mobile, level)
end
